// <auto-generated />
namespace DisSunChat.Repos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ExtendDBToIdentityMd5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtendDBToIdentityMd5));
        
        string IMigrationMetadata.Id
        {
            get { return "202003260726043_ExtendDBToIdentityMd5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
